### ISSUE TITLE
history for this one as well?

### ISSUE THREAD

**Issue by wchristian** [devel-chm/OpenGL-Array#2]
I can do the same thing as for -GLUT here as well if you care about it.

**Comment by devel-chm** [comment]
Sure, thank you.

**Comment by wchristian** [comment]
Aight, set it up in https://github.com/devel-chm/OpenGL-Array/tree/history Please have a look for sanity-check and let me know when i should force-push that to master.

**Comment by devel-chm** [comment]
Looks good from here.  Go ahead.

**Comment by wchristian** [comment]
Force-push done. You'll need to do:

- git fetch
- git checkout master
- git diff master..origin/master
- git reset --hard origin/master
